name: 🧪 Run Postman Tests

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 📁 List project files (Debug Step)
        run: |
          echo "📂 Root Directory:"
          ls -R

      - name: 🧪 Install Newman and htmlextra reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: 🚀 Run Postman Tests
        run: |
          newman run Product-Store-API-Test/collection/ProductStore.postman_collection.json \
          -d Product-Store-API-Test/data/orders.csv \
          -r htmlextra \
          --reporter-htmlextra-export Product-Store-API-Test/reports/final-report.html

      - name: 📤 Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: postman-html-report
          path: Product-Store-API-Test/reports/final-report.html
